### ISSUE TITLE
Word limited on imported description text?

### ISSUE THREAD

**Issue by stevieflow** [NeonOpenAG/oagtoolbox#145]
The tool chain seems to truncate the description text in the interface:

http://www.openag.org.uk/classifier/1/XM-DAC-41108-1100001483

vs

http://d-portal.org/q.html?aid=XM-DAC-41108-1100001483

**Comment by tobybatch** [comment]
Well that's curious.  I'll need to find at what point the text is truncated.

@harryharold we need this in the next sprint
