### ISSUE TITLE
Add suggestions from description text automatically

### ISSUE THREAD

**Issue by stevieflow** [NeonOpenAG/oagtoolbox#146]
See http://www.openag.org.uk/classifier/1/XM-DAC-41108-1100001483

I get no suggestions.  If I copy and paste the description text into the box, I then get Livestock and rice suggested

**Comment by tobybatch** [comment]
@stevieflow I think may be an issue with the bulk classifier.  I need to check but my first guess is the classifier is iterating over the XML and classifying the documents but isn't classifying descriptive text embedded in text nodes.

@harryharold we need this in the next sprint

**Comment by tobybatch** [comment]
I will check if text in the XML is classified as well as the linked documents.

**Comment by harryharrold** [comment]
Route to reproduce:

1) Download the XML file at https://webapps.ifad.org/iati/ifad_activities.xml
2) Upload to http://www.openag.org.uk/
3) Choose the Classifier
4) Find in page the activity "Rural Development: Al-Dhala Community Resources Management Project"
5) Observe the absence of a "View suggestions" button
6) Copy the description from that activity
7) Choose to "Add more information"
8) Paste the description in to the text box.
9) Click read.
10) Observe the resulting suggestions...

**Comment by tobybatch** [comment]
Mailed Dave Hollander to check if the classifier endpoint reads embedded text

**Comment by tobybatch** [comment]
on develop
