### ISSUE TITLE
Access to other files

### ISSUE THREAD

**Issue by stevieflow** [NeonOpenAG/oagtoolbox#148]
It seems that any user can access files submitted through the toolchain - either via : http://www.openag.org.uk/download/9 - or my manipulating the in-play URL

Would be good to establish initially is this is the case, and then decide on what needs to be in place

**Comment by tobybatch** [comment]
@stevieflow yep, that's right.  You can get documents by freaking the URL.  We don't intend to change that in the current version.

**Comment by harryharrold** [comment]
@stevieflow - that's only true for the duration a document is on the site - once deleted, those links  *either* 404, or are replaced as new documents are uploaded. @tobybatch is quite right to say we're not changing that in this sprint. We *should* add that info to a "terms" page, though.
