### ISSUE TITLE
Improve button labels on Check and improve page

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#153]
QV Feedback on "what do these buttons do"

**Comment by harryharrold** [comment]
Commit https://github.com/NeonOpenAG/oagtoolbox/commit/b1d93eec964134190e79ad71f37ccaa893eada4f

**Comment by harryharrold** [comment]
https://github.com/NeonOpenAG/oagtoolbox/pull/205
