### ISSUE TITLE
Develop a new tactic to encourage users to improve data

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#155]
The arrow on the check and improve page was not always understood.

**Comment by harryharrold** [comment]
Also - arrow not consistent in styling with other interface elements.

**Comment by reidmporter** [comment]
Increase size of exclamation icons and check marks to reduce need for arrow?

**Comment by tobybatch** [comment]
And take the arrow away

**Comment by tobybatch** [comment]
http://develop.openag.org.uk/improveYourData/2
