### ISSUE TITLE
Allow re-classification/geocoding of documents

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#158]
Allow a processed document to be re run through the classifier/geocoder

**Comment by tobybatch** [comment]
QV "Also it isn't possible to go back and re-take the agrovoc check - that has now disappeared. Can I do it again?"

**Comment by tobybatch** [comment]
http://158.openag.org.uk/

**Comment by harryharrold** [comment]
Please do not show the ↻ Re-Geocode and ↻ Re-Classify buttons.

Please expand the info class automatically when *some* improvement has taken place.

Please replace the button texts with "Further improve your tagging" and "Further improve your geo-coding" respectively.

Then we'll test again...

**Comment by tobybatch** [comment]
http://develop.openag.org.uk/app_dev.php
