### ISSUE TITLE
Investigate how to demonstrate improvements in the data

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#161]
Levels of improvement

**Comment by tobybatch** [comment]
Get data about what has changed and how it has changed.

**Comment by reidmporter** [comment]
"You've looked at all 100 of your activities (100%), but you've only coded 50 of them (50%, but 100% of relevant ag activities"?

**Comment by tobybatch** [comment]
http://161.openag.org.uk/improveYourData/2

@harryharrold What do you think.  These are raw numbers, we can use colours/percentages?

**Comment by harryharrold** [comment]
Split the date we can know by relevance to geo-coding and classification, and use *that* data to manage where those calls to action appear.

**Comment by tobybatch** [comment]
http://develop.openag.org.uk/app_dev.php
