### ISSUE TITLE
Add additional data descriptors to geolocation suggestions

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#163]
QV "Can we populate the box with additional info - admin level, population, etc. - from Geonames for context?"

Adding additional text fields will allow extra information to be included.

**Comment by tobybatch** [comment]
This makes no sense unless we are editing existing nodes.

**Comment by harryharrold** [comment]
Per discussion - please add the text we have in the feature designation element from the xml - so from <feature-designation code="ADM1"/><point> add the code in brackets on a new line after the name of the province -

(ADM1)

in this example.

 and the rest of the data in an html comment, as discussed.
