### ISSUE TITLE
Better explanation of the D-Portal preview page

### ISSUE THREAD

**Issue by tobybatch** [NeonOpenAG/oagtoolbox#169]
Are all the questions are really the same thing?  Make it clear this is a separately hosted d-portal preview. 

QV
"Dashoard of project ?
Data transfer/check
Seeing it live online - cool if it's real (not updated once a day)
No pipeline projects published
I can look for tags and see projects with activities related to my query
Your data are being presented in d-portal so that you can review/check
result of all actions
numbers of data available
explorer
Data is published and available for users
a new project was classified according to IATI
d-portal preview of my data so far. This is very cool.
You’ve embedded the d-portal preview within your site. Assume that you would show how this data would look on d-portal. Probably used quality check, since more people use d-portal to check their activity files.
Again cheating because I know, but it's what your info would look like on d-portal but not actually d-portal. Not super clear though. Make preview text day example or maybe just make text bigger and more obvious because it's missed. Or maybe say preview and underneath not really d-portal.
Standard project numbers. Not sure how unique.
previews my data in the D-portal interface
D-portal is reading in an iati publishers Data and showing activities within the time period at the top and disaggregating it by the dates in the data.
See the selection of activeties here
An embed in an iframe of d-portal to preview the data you just input
I knew this before - but this seems to show a Preview of d-portal in an i-framey thing."

**Comment by harryharrold** [comment]
In https://github.com/NeonOpenAG/oagtoolbox/pull/183
