### ISSUE TITLE
Handling "No suggestions" more elegantly.

### ISSUE THREAD

**Issue by harryharrold** [NeonOpenAG/oagtoolbox#220]
Our new text for adding more information is no longer fit for purpose in cases where there *are* no suggestions, and needs improvement for that specific case. 

See below.

![image](https://user-images.githubusercontent.com/907596/34037715-bbe6df54-e181-11e7-8642-675fdbf3c921.png)

**Comment by tobybatch** [comment]
@harryharrold Chat on Tuesday about this?  Do need new function or just new copy?
